### ISSUE TITLE
Launching server using runtime ~/Sites/svelte-language-server/bin/server.js failed

### ISSUE THREAD

**Issue by lumixraku** [UnwrittenFun/svelte-language-server#11]
The vscode says "Launching server using runtime ~/Sites/svelte-language-server/bin/server.js failed"

Is there any log to check?

My node version is 8.9.4  and my OS is macOS 10.13.3 (17D47)

**Comment by JohnnyFun** [comment]
This might not be the answer to your question, but if it's any help, here's how I debug the server (there's _probably_ a better way lol, but this works great for now):

- I'm using vscode, so I cloned `svelte-language-server` _and_ `svelte-vscode`
- npm i in both of them...
- `npm run watch` to compile typescript files
- Then I changed `svelte-vscode` to point to my cloned repo for `svelte-language-server`. So in svelte-vscode/src/extensions.ts, change `serverModule` to point to something like: `        path.join('../../dev/svelte-language-server/bin/server.js')` instead of the node_modules location
- Then put a breakpoint at the start of svelte-vscode's activate function (prior to starting the server) and run "Launch Client" (F5)
- wait for it to hit your breakpoint, then open up svelte-language-server in a separate vscode editor
- put a breakpoint at the start of `src/server.ts.startServer()`
- hit F5 there to "Attach to Server"
- then switch back to vs-code and continue from your breakpoint so it starts the server
- soon your server breakpoint will be hit too since it will attach to the server once it's started!

Like I said, probably a smoother way, but yar. Enjoy!

**Comment by JohnnyFun** [comment]
Otherwise, if you're simply using the extension, you might try uninstalling it and reinstalling it. Good luck!
